version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pot_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  next-app:
    container_name: pot-api
    build:
      context: ./backend-api
      dockerfile: dev.Dockerfile

    # Set environment variables directly in the docker-compose file
    environment:
      ENV_VARIABLE: ${ENV_VARIABLE}
      NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
      DATABASE_URL: ${DATABASE_URL}

    # Set environment variables based on the .env file
    env_file:
      - .env
    volumes:
      - ./backend-api/app:/app/app
      - ./backend-api/public:/app/public
    restart: always
    ports:
      - 3000:3000

volumes:
  postgres_data:
